server:
  port: 9000
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:19092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: com.demo.serde.JSONSerde
      properties:
        isolation.level: read_committed
        spring:
          json:
            trusted:
              packages: com.demo.commands,com.demo.events
      enable-auto-commit: false
    producer:
      bootstrap-servers: localhost:19092
      transaction-id-prefix: tx.
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.demo.serde.JSONSerde
      properties:
        enable.idempotence: true
    listener:
      ack-mode: MANUAL
